"""Create board table

Revision ID: fa6894bc5eb5
Revises: 2b463ca30d96
Create Date: 2019-10-01 23:17:38.951741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa6894bc5eb5'
down_revision = '2b463ca30d96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('number', sa.Integer(), nullable=False),
                    sa.Column('counter', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('id'))

    op.create_index(op.f('ix_board_number'), 'board', ['number'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f('ix_number_number'), table_name='number')
    # op.drop_index(op.f('ix_number_counter'), table_name='number')
    # op.drop_table('number')
    # ### end Alembic commands ###
    pass
